import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createHash } from "node:crypto";
import { supportFooter } from "./support-footer.ts";
const root = import.meta.dir;
const output = resolve(root, "dist");
const kit = dirname(fileURLToPath(import.meta.resolve("@hraness/design-kit/paper-theme.css")));
await rm(output, { recursive: true, force: true });
await mkdir(resolve(output, "design"), { recursive: true });
for (const name of ["styles.css", "icon.png", "apple-icon.png", "robots.txt", "sitemap.xml", "llms.txt"]) await cp(resolve(root, name), resolve(output, name));
const html = await readFile(resolve(root, "index.html"), "utf8");
const footerMarker = "<!-- hraness-site-footer -->";
if (html.split(footerMarker).length !== 2) throw new Error("Expected one shared footer slot.");
await writeFile(resolve(output, "index.html"), html.replace(footerMarker, supportFooter()));
await cp(fileURLToPath(import.meta.resolve("@hraness/site-footer/stylex.css")), resolve(output, "footer.css"));
const files = ["paper-theme.css", "product-marketing-preset.css", "lantern-material.css", "appearance-menu.css", "fonts.css"];
for (const name of files) await cp(resolve(kit, name), resolve(output, "design", name));
await cp(resolve(kit, "fonts/nebula-sans"), resolve(output, "design/fonts/nebula-sans"), { recursive: true });
await cp(resolve(kit, "fonts/instrument-serif"), resolve(output, "design/fonts/instrument-serif"), { recursive: true });
await cp(resolve(kit, "marketing-assets"), resolve(output, "design/marketing-assets"), { recursive: true });
await cp(resolve(kit, "../LICENSE"), resolve(output, "design/LICENSE"));
const result = await Bun.build({ entrypoints: [resolve(root, "appearance.ts")], outdir: output, naming: "appearance.js", target: "browser", format: "iife", minify: true });
if (!result.success) throw new AggregateError(result.logs, "Appearance bundle failed");
const pkg = JSON.parse(await readFile(resolve(kit, "../package.json"), "utf8"));
await writeFile(resolve(output, "design/source.json"), JSON.stringify({ package: pkg.name, version: pkg.version, files: Object.fromEntries(await Promise.all(files.map(async name => [name, createHash("sha256").update(await readFile(resolve(output, "design", name))).digest("hex")]))) }, null, 2));
console.log(`Built Vhalla with ${pkg.name}@${pkg.version}.`);
