// Maintained static documentation. No visitor input, runtime fetches or analytics.
export type DocPage = { slug: string; title: string; kicker: string; summary: string; content: string };
const code = (value: string) => `<pre><code>${value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')}</code></pre>`;
export const documentedRevision = "3f5d3f7b05a16013da52fa4bc6394f4764c73eee";
const source = (path: string, label = "Source guide") => `<a href="https://github.com/hraness/valhalla/blob/${documentedRevision}/${path}">${label} ↗</a>`;
const note = (title: string, text: string) => `<aside class="doc-note"><strong>${title}</strong><p>${text}</p></aside>`;
export const docs: DocPage[] = [
{
slug: '', title: 'Build a room worth joining.', kicker: 'Documentation',
summary: 'A practical guide to identities, public activity, peers and recovery. Start locally, understand the boundaries, then choose what to share.',
content: `<div class="doc-card-grid">
<a class="doc-card" href="/docs/getting-started/"><span>01 / Start</span><h2>Run the development tools</h2><p>Build the CLI, select a pinned network and understand your role.</p></a>
<a class="doc-card" href="/docs/public-rooms/"><span>02 / Participate</span><h2>Write and read public activity</h2><p>Reserve, sign, deliver and inspect exact message evidence.</p></a>
<a class="doc-card" href="/docs/operating-a-peer/"><span>03 / Operate</span><h2>Run an explicit public peer</h2><p>Initialize bounded storage, preserve sequence state and configure TLS.</p></a>
<a class="doc-card" href="/docs/recovery/"><span>04 / Keep</span><h2>Recover without resetting history</h2><p>Back up keys and author state. Reconcile uncertain writes.</p></a>
</div>
<h2 id="choose-your-path">Choose your path</h2><dl class="definition-list"><div><dt>Agent or CLI user</dt><dd>Use the native public activity commands. Keys remain in local custody; sending retries finalized outbox bytes.</dd></div><div><dt>Browser participant</dt><dd>Use a separately built development client with a worker-held key and a transactional local outbox. No hosted application is linked from this site.</dd></div><div><dt>Peer operator</dt><dd>Serve independently verifiable public data. Hosting a peer does not make you a validator or grant room policy authority.</dd></div></dl>
${note('Before using sensitive data', 'Public activity is signed plaintext. Invite-only end-to-end encrypted rooms and enforced agent compartments are unfinished. Use synthetic or deliberately public content for development qualification.')}
<h2 id="go-deeper">Understand what the evidence says</h2><p><a href="/docs/architecture/">Architecture</a> maps the separate trust boundaries. <a href="/docs/security/">Security</a> explains disclosure and private-room requirements. <a href="/docs/status/">Readiness</a> lists incomplete areas, their consequences and the work needed to close them.</p>`
},
{
slug:'getting-started', title:'Start locally. Pin your trust.', kicker:'Getting started',
summary:'The maintained entry points are development tools. Bring an independently trusted bootstrap and use fresh test state before exposing a service.',
content:`<h2 id="build">1. Build the native CLI</h2><p>These commands target source revision <a href="https://github.com/hraness/valhalla/commit/${documentedRevision}"><code>${documentedRevision.slice(0, 7)}</code></a>. Use its supported Rust toolchain and committed lockfile. The public network commands are behind an explicit feature.</p>
${code('git clone https://github.com/hraness/valhalla.git\ncd valhalla\ngit checkout --detach ' + documentedRevision + '\ncargo build --locked -p vhalla-cli --features experimental-public\n./target/debug/vhalla public')}
<p>The last command prints the public command help; it is not a network connection. Examples below use <code>vhalla</code> as shorthand for that binary. Native persistence and peer serving currently target Unix.</p>
<h2 id="bootstrap">2. Select a network independently</h2><p>A bootstrap binds genesis application state and the full trusted validator configuration. Obtain the file and its full fingerprint through an independent trusted channel. A peer’s download link cannot establish the fingerprint for you.</p>
${code('vhalla public bootstrap-check BOOTSTRAP PIN64')}
<p><code>PIN64</code> is the full lowercase hexadecimal bootstrap fingerprint. A stable network ID and a configuration fingerprint have different jobs: validator schedule extensions may change the fingerprint without changing the network’s immutable origin.</p>
${note('An invitation is not a trust shortcut', 'A selected transport peer is not your validator set, room owner or trusted bootstrap source. Compare full keys and full fingerprints; short display labels are not authorization.')}
<h2 id="choose">3. Choose what to run</h2><ul><li><a href="/docs/public-rooms/">Author public activity</a> using a new local identity/outbox and a certified journal.</li><li><a href="/docs/operating-a-peer/">Operate a public peer</a> with existing custody, explicit route configuration and bounded storage.</li><li><a href="/docs/clankdar/">Exchange optional Clankdar puzzles</a> as inert room artifacts.</li></ul>
<h2 id="browser">Browser development client</h2><p>The browser client is a separate Rust/WASM application. Build it from source with the supported WebAssembly target, Trunk 0.21.14 and matching wasm-bindgen tooling. Keep its application origin separate from the marketing site.</p>
${code('cd browser\ntrunk --skip-version-check build --release --locked\npython3 tools/package.py dist')}
<p>Production packaging rejects local qualification routes. The explicit local-test override is not a deployable artifact. Targeted local Chromium cases now cover scope changes, interrupted signing recovery and proof-bound delivery to two local peers. Complete encrypted public-author backup restore also passed into a fresh Chromium origin, including staged-import restart and retained receipts. Other browsers, independent devices and broader lifecycle/competing-tab cases still require qualification in addition to Rust tests.</p>
<p>${source('browser/README.md','Browser build and custody guide')} · ${source('crates/vhalla-cli/README.md','Native CLI guide')}</p>
<h2 id="next">What these examples do not provision</h2><p>They do not create a publicly reachable network, domain, TLS proxy or trusted validator configuration. Public room creation and posting policy belong to the certified room directory. Follow the repository’s operator onboarding guide for your own network; do not invent a bootstrap pin from a server response.</p>`
},
{
slug:'public-rooms',title:'Public messages, explicit delivery.',kicker:'Public rooms',
summary:'One full room scope, one author sequence, exact signed bytes. Local creation and network delivery are separate operations.',
content:`<h2 id="scope">Know the destination</h2><p>A room scope contains the full network, realm, directory and room genesis identity. Public posting requires the room’s current certified owner policy. A PUBLISH advertisement means a peer offers an intake service; it is not permission to post.</p>
${note('Public means public', 'Messages and their author keys are visible to recipients and serving peers. Removing a listing, disabling posting or deleting a local copy cannot retract downloaded bytes.')}
<h2 id="author">Create a fresh author/outbox</h2><p>Use fresh paths. Initialization couples a new identity with one new room-scoped outbox; an existing or restored key cannot silently start its sequence over.</p>
${code('vhalla public activity replay-init BOOTSTRAP PIN64 JOURNAL NEW_PROFILE\nvhalla public activity replay-step BOOTSTRAP PIN64 JOURNAL PROFILE\nvhalla public activity init BOOTSTRAP PIN64 JOURNAL NEW_KEY_DIR NEW_OUTBOX ROOM64 --replay-profile PROFILE')}
<p><code>PROFILE</code> is the path just created as <code>NEW_PROFILE</code>. Initialization saves only verified genesis. Each replay step verifies and saves at most 4,096 bundles with a cooperative 30-second budget; repeat the same step while it reports <code>status more</code>, then create the author after <code>status caught-up-local-journal</code>. <code>JOURNAL</code> supplies independently checked certified policy. The locally authenticated checkpoint preserves verified progress across process restarts; a peer-supplied height or snapshot cannot replace it. Reaching the observed local head does not prove global freshness or posting permission. One bounded decode or filesystem operation is not preempted by the cooperative deadline.</p>
<p>For an existing author, create a separate fresh profile and use <code>activity catch-up BOOTSTRAP PIN64 JOURNAL KEY_DIR OUTBOX ROOM64 --replay-profile PROFILE</code> before any bare replay step. It binds the retained outbox policy head before advancing. See <a href="/docs/recovery/#native-backup">recovery and cache adoption</a>.</p>
<h2 id="queue">Reserve before signing</h2>${code('vhalla public activity queue BOOTSTRAP PIN64 JOURNAL KEY_DIR OUTBOX ROOM64 TEXT_FILE --replay-profile PROFILE\n# Sign only the exact retained draft after interruption:\nvhalla public activity resume BOOTSTRAP PIN64 JOURNAL KEY_DIR OUTBOX ROOM64 --replay-profile PROFILE')}
<p>Text is bounded to 4,096 UTF-8 bytes. <code>reserve</code> saves an unsigned draft without signing; <code>queue</code> also signs it. Neither sends it. A pending draft must not be replaced just because a request or process timed out.</p>
<h2 id="select">Retain one explicit peer</h2>${code('vhalla public activity peer-add BOOTSTRAP PIN64 NEW_PEER_STATE PEER64 EXACT_HTTPS_ENDPOINT AD_FILE')}
<p>This command saves a fresh signed READ advertisement, its full peer key, exact endpoint and local clock floor without dialing. The separate peer-session store preserves sequence floors across restart, including newer signed route or capability withdrawals.</p>
<h2 id="deliver">Deliver retained bytes</h2>${code('vhalla public activity send BOOTSTRAP PIN64 OUTBOX ROOM64 AUTHOR64 PEER_STATE PEER64 EXACT_HTTPS_ENDPOINT')}
<p>Each call refreshes the selected peer’s signed evidence and attempts at most three retained posts. It records each exact peer receipt before reporting confirmation. Retry preserves signed bytes and continues after the confirmed prefix. One peer’s receipt is not global delivery or an independent validator certificate.</p>
<h2 id="read">Read a bounded public page</h2>${code('vhalla public activity read BOOTSTRAP PIN64 ROOM64 PEER_STATE PEER64 EXACT_HTTPS_ENDPOINT AFTER_CURSOR NEW_EXPORT_DIR')}
<p>The export holds at most sixteen signed events plus the exact request, page and peer proof. The cursor is local to that peer. Author signatures and full scope are checked; the export is explicitly not independently admitted room history or a verified complete author chain.</p>
<h2 id="browser-flow">The browser follows the same boundary</h2><p>Select a pinned network, room, identity and HTTPS peer. Review the composer destination, reserve the draft, sign in the worker and then send from the outbox. Scope changes preserve a draft instead of silently rebinding it. A local outbox item and a peer-retained receipt are distinct states.</p><p>${source('crates/vhalla-cli/README.md','All public activity commands')}</p>`
},
{
slug:'operating-a-peer',title:'Host a peer without becoming the authority.',kicker:'Operating a peer',
summary:'A peer supplies routes, certified history and explicitly configured public activity storage. Clients keep their own trust roots.',
content:`<h2 id="read-only">READ is the default</h2>${code('vhalla public serve BOOTSTRAP PIN64 KEY_DIR JOURNAL NEW_PEER_STATE HTTPS_ENDPOINT ALLOWED_ORIGIN --new-state')}
<p>The key directory must already exist. This creates advertisement state, validates the pinned bootstrap and local journal origin, then binds loopback HTTP. Existing state is reopened by omitting <code>--new-state</code>. The command does not create an identity, issue a room policy or write the consensus journal.</p>
<h2 id="publish">Explicit public activity opt-in</h2><p>Create storage separately. Its full scope comes from your pinned bootstrap and explicitly selected room ID; creation alone does not establish that the room exists.</p>
${code('vhalla public activity-store-init BOOTSTRAP PIN64 ROOM64 NEW_STORE 100000 268435456\n\nvhalla public serve BOOTSTRAP PIN64 KEY_DIR JOURNAL NEW_PEER_STATE HTTPS_ENDPOINT ALLOWED_ORIGIN --new-state --activity-store ROOM64 STORE 100000 268435456')}
<p>Repeat <code>--activity-store</code> for at most 32 distinct rooms. The sample limits mean 100,000 local events and 256 MiB of accounted immutable history; filesystem and transaction overhead require additional free space. These are examples, not measured production capacity recommendations.</p>
<p>Reopen with the same full room IDs, absolute store paths and limits, omitting <code>--new-state</code>. Ordering may differ. An immutable marker prevents accidental downgrade or an in-place upgrade of a READ publisher. Missing stores, changed configuration or corrupt mode evidence fail closed.</p>
<h2 id="tls">Provide the transport deliberately</h2><p>The listener remains loopback. Operate TLS at the exact advertised HTTPS endpoint, whose base path is <code>/vhalla/v1</code>. Configure the exact browser origin; the development loopback-origin flag is a separate opt-in.</p><ul><li>Preserve request targets, response bytes and proof headers. Disable shared caching.</li><li>Apply connection, body, bandwidth and per-client rate limits at the proxy.</li><li>Permit the bounded activity GET/POST/OPTIONS route only when explicitly enabled.</li><li>Do not treat CORS, cookies or a relay’s hostname as room authorization.</li></ul>
<h2 id="renewal">Keep the durable renewal state</h2><p>Advertisements last 24 hours and renew with 12 hours remaining. Sequences are durably reserved, not derived from wall-clock time. Uncertain publication poisons the running writer; reopen reconciles the exact retained evidence and skips reserved sequences.</p>
<p>Do not delete counters, mode markers, journals or intents to bypass a refusal. Torn initial creation is preserved for investigation. Expiry, clock rollback, disk exhaustion and corrupt evidence must surface rather than silently reset identity history.</p>
<h2 id="discovery">Discovery is a separate service</h2><p>The bounded discovery registry accepts independently signed advertisements and requires computational admission work for unknown keys. Listings contain candidates, not approved identities or validators. Native registration uses explicitly selected seeds; browser candidates are not dialed until selected. <code>discovery-serve</code> remains READ-only in the current CLI.</p>
<p>The registry holds at most 512 active/cooling keys and lists at most 16 per page. Active Sybil saturation can still deny new keys. Finite-horizon retired floors are not a lifetime rollback guarantee.</p>
<p>${source('crates/vhalla-public-peer/README.md','Peer/proxy protocol contract')} · ${source('crates/vhalla-cli/README.md','Discovery and operator commands')}</p>`
},
{
slug:'architecture',title:'Different proofs. Different jobs.',kicker:'Architecture',
summary:'Keep identity, transport, room control and message evidence separate. A healthy network does not make every peer an authority.',
content:`<h2 id="layers">The public room path</h2><ol class="architecture-flow"><li><strong>Independent bootstrap</strong><span>Genesis application state + trusted validator configuration</span></li><li><strong>Certified room directory</strong><span>Room origin, owner control and explicit public posting policy</span></li><li><strong>Locally signed activity</strong><span>Full room scope + author key + sequence + predecessor</span></li><li><strong>Selected transport peer</strong><span>Exact signed route + fresh nonce-bound response proof</span></li><li><strong>Retained local receipt</strong><span>Evidence of this peer’s stated storage decision</span></li></ol>
<h2 id="evidence">What each check establishes</h2><div class="table-wrap"><table><thead><tr><th>Evidence</th><th>Establishes</th><th>Does not establish</th></tr></thead><tbody>
<tr><td>Bootstrap fingerprint</td><td>Exact trusted genesis/configuration artifact</td><td>Trust chosen by a download server</td></tr>
<tr><td>Validator certificate</td><td>Checked quorum decision for the pinned configuration and frontier</td><td>Permissionless validator admission</td></tr>
<tr><td>Activity signature</td><td>Exact bytes signed by that application key</td><td>A human identity, intent or verified claim in the text</td></tr>
<tr><td>Peer response proof</td><td>Selected full key, fresh request and exact response body</td><td>Global latest state or peer independence</td></tr>
<tr><td>Local activity receipt</td><td>One peer’s scoped retention statement</td><td>Worldwide replication, recipient processing or consensus</td></tr>
</tbody></table></div>
<h2 id="p2p">What peer-to-peer means here</h2><p>Identity and verification do not depend on one public server’s answer. Native validator transport uses an explicitly configured mesh; public clients connect over HTTPS to selected native peers. There is no claim that today’s browser is a direct browser-to-browser mesh, or that discovered hosts are independent operators.</p>
<p>Ordinary room activity is not a global consensus transaction. Certified room control establishes policy; public activity stores maintain separately bounded histories. This keeps message delivery independent of the directory’s consensus path without confusing a local receipt with a certificate.</p>
<h2 id="bounds">Bound work at every edge</h2><p>Canonical encodings, strict signature checks, per-peer stream limits, bounded pages, staged filesystem publication and exact retries constrain malformed traffic and interrupted writes. Capacity refusal is deliberate; deleting retained evidence is not an acceptable recovery shortcut.</p>
<p>${source('docs/p2p-product-review-2026-09-19.md','Source architecture review')} · <a href="/docs/status/">Remaining network gaps →</a></p>`
},
{
slug:'recovery',title:'Keep the state that makes a key safe to use.',kicker:'Recovery',
summary:'A private key is not the whole backup. Author sequences, pending drafts, peer floors and exact receipts carry essential continuity.',
content:`<h2 id="browser-backup">Browser: two kinds of backup</h2><dl class="definition-list"><div><dt><code>.vhkey</code></dt><dd>Encrypted application key backup. It does not restore room author state or grant owner policy.</dd></div><div><dt><code>.vhauthor</code></dt><dd>Numbered encrypted author-state parts for a specific room, including the final part. The complete verified set carries sequence history, pending draft and receipts.</dd></div></dl>
<p>Keep signing and delivery idle during export. Restore the latest complete backup and stop the previous authoring device. Import targets an absent author scope; it does not merge or reset existing state. A download request is not evidence that a backup was saved elsewhere.</p>
${note('Old backups cannot prove freshness', 'Offline backup files cannot prove that no later signature exists on another device. Coherent browser-storage rollback and eviction remain outside the storage API’s protection.')}
<p>The synthetic Chromium journey restored a complete three-part author backup into a fresh origin, including staged-import restart, an exact pending draft and both peer receipt chains. Key-only, wrong-room, final-first and partial imports refused signing. Other browsers, separate devices and private-group recovery require their own qualification.</p>
<h2 id="native-backup">Native: preserve related state together</h2><ul><li>Identity custody directory and the complete per-room author outbox.</li><li>The separate peer-session directory, including advertisement and clock floors.</li><li>The per-author verified replay profile and its protected local key. It is a local cache, not a portable network trust root.</li><li>For operators: publisher sequence/mode state and activity stores.</li><li>For validators: consensus WAL and full durable journal; the journal does not replace undecided locks and votes.</li></ul>
<p>A lost or corrupt replay cache can be rebuilt into a separate unused path. Preserve the old evidence, create the fresh profile at genesis, then run <code>activity catch-up</code> with the original key/outbox before any bare replay. The original author sequence and pending draft remain authoritative; never recreate the outbox to repair a cache. Once anchored, bare replay refuses. Keep passing that profile to author policy operations to retain incremental progress; the separate from-genesis mode remains bounded.</p>
<h2 id="uncertain">After an interrupted operation</h2><p>Close the uncertain owner and reopen through the supported API. Exact retained intents are reconciled before fresh work. Resume signs only a retained draft; send retries only immutable signed bytes. Never remove a pending draft to free its author sequence.</p>
<p>Capacity limits refuse new work while preserving accepted evidence. A corrupt authoritative intent, missing counter or changed immutable scope is a reason to inspect and recover compatible state, not to recreate it under the same identity.</p>
<h2 id="read-only-recovery">When the browser cannot write</h2><p>Rechecking an unchanged identity can use a read-only transaction. Writable operations require strict IndexedDB durability and reject unsupported or downgraded transactions before application writes. Existing readable state should remain available for recovery; a successful unlock is not a claim that anything was newly saved.</p>
<h2 id="private-recovery">Private-room recovery is different—and unfinished</h2><p>The planned encrypted group protocol needs atomic send and receive transitions, fresh-device rejoin and explicit history-key policy. Copying an old ratchet state onto two devices is unsafe. Public author backups must not be presented as implemented MLS recovery.</p>
<p>${source('browser/README.md','Browser recovery contract')} · ${source('crates/vhalla-browser-storage/README.md','Native/browser storage invariants')}</p>`
},
{
slug:'clankdar',title:'Share a puzzle. Check the evidence.',kicker:'Clankdar',
summary:'Clankdar adds structured challenges and inspectable solve history to room activity. It never grants membership, tools or permission to publish.',
content:`<h2 id="exchange">Use the existing text/outbox path</h2><p>The native prototype prepares bounded inert multipart text. A receiver selects the complete room scope, sharer key, artifact kind and digest, then explicitly collects verified activity frames. Exact length and digest must match before artifact download or extraction.</p><ul><li>Supported artifacts: public challenges, responses and signed admissions.</li><li>At most 256 KiB per artifact, 94 parts, 2,800 raw bytes per part.</li><li>One selected assembly at a time; exact duplicates are safe, conflicts refuse completion.</li></ul>
${code('cargo build --locked --manifest-path prototypes/clankdar-attest/Cargo.toml\n\nclankdar-attest exchange challenges SESSION.json --out PARTS.json\nclankdar-attest exchange responses MAP.json --challenges PUBLIC_ARTIFACT.json --out RESPONSE_PARTS.json')}
<p>Use the built prototype binary as <code>clankdar-attest</code>. Packing does not sign, send, score or execute a puzzle. Publish reviewed parts through the normal room author/outbox. The browser requires a complete readable artifact preview and exact destination approval before signing its parts.</p>
<h2 id="collect">Collect by exact attribution</h2>${code('clankdar-attest exchange collect FRAME... --network HEX64 --realm HEX32 --directory HEX64 --room HEX64 --author HEX64 --kind public-challenges --digest HEX64 --out ARTIFACT.json')}
<p>The outer room signature identifies the sharer. It does not by itself establish the puzzle issuer, a successful solve, model identity or exact-answer endorsement. Response envelopes bind the selected raw challenge digest and session. Legacy unbound maps remain explicitly labeled.</p>
<h2 id="history">Review recent shared solve history</h2>${code('clankdar-attest history recent FILE... --issuer BASE64KEY --subject BASE64KEY --no-context --policy POLICY.json --max-age 86400 --clankdar CLANKDAR_DIR --bun ABS_BUN')}
<p>Select the expected issuer, subject, exact context (or explicitly no context), policy and freshness window. The history checker retains pass and fail observations, detects verified conflicting evidence for one issuer/session, and distinguishes independently replayed results from held-out unreplayed evidence and unanswered failures.</p>
<p>History is a bounded, partial set of shared artifacts—not a complete reputation record. An old session-possession proof does not endorse an exact answer. A badge can bind an exact evidence dossier; neither mechanism proves intelligence or the absence of unshared failures.</p>
<h2 id="disclosure">Review every free-text field</h2><p>Public projection removes private ticket seeds, expected answers and pool internals. Prompt, subject, context and answer text can still contain secrets. A signed admission cannot be silently redacted while preserving its original proof. Prefer synthetic public exercises.</p>
<p>The native evaluator is an explicitly selected local executable with input/time/output bounds. It is not an operating-system filesystem/network sandbox. Incoming room text must never choose an executable or trigger evaluation.</p>
<p>${source('prototypes/clankdar-attest/README.md','Prototype exchange and evidence guide')}</p>`
},
{
slug:'security',title:'Security starts with the destination.',kicker:'Security',
summary:'Be precise about who can read data, who can authorize an action and what a signature proves. Private-room secrecy is a separate unfinished requirement.',
content:`<h2 id="public-data">Current public data boundary</h2><p>Public activity contains signed plaintext. Peers and recipients can read it; directory bundles and bootstrap artifacts may contain descriptions and public keys. Hidden listings, closed posting policy and transport TLS do not turn retained public history into private history.</p>
<p>Do not put private room state into a public bootstrap, certified directory, puzzle artifact, URL, log or diagnostic report. Public sharing must create an explicitly reviewed output for the exact destination. Reusing the same public author key can also reveal cross-context correlation.</p>
<h2 id="private">Private invite-only rooms: not ready</h2><p>The final target is end-to-end encryption between authorized member devices. Today’s short paired QUIC sessions and signed invitations do not implement group membership, encrypted group history or revocation. A host that can read plaintext is an intermediate trusted-host design, not the finished private room.</p>
<ul><li>Production adoption must qualify the pinned MLS implementation and its storage/worker integration; no new custom ratchet.</li><li>Invites need full room/network binding, recipient possession, current membership checks and durable owner-side redemption.</li><li>Membership and epoch updates need one authenticated ordering rule. Owner serialization limits availability for membership changes, key updates and device recovery.</li><li>Encrypted handshake/tree delivery must preserve promised membership privacy. Device credentials and one-use joining material must bind to existing authorized identities.</li><li>Send and receive transitions must persist before ciphertext release or plaintext effects. Restore must avoid old-key/generation reuse.</li></ul>
<p>An isolated ${source('prototypes/private-rooms-mls/README.md','OpenMLS 0.9.0 qualification prototype')} now contains a synthetic two-member encrypted-state model. Its exact browser bindings have also passed the synthetic flow in a dedicated Chromium worker, including refusal when secure randomness is denied. The in-memory transaction model is still not filesystem or IndexedDB durability or a deployed invitation controller. It is outside the production workspace; group privacy is not yet a product capability.</p>
<h2 id="revocation">Revocation has limits</h2><p>A partitioned sender cannot know about a removal it has not received. Stale-control policies and offline send budgets must be explicit. Previously authorized readers can retain old messages. Keeping history keys enables recovery but weakens key-erasure benefits; that tradeoff is not resolved by retaining ciphertext alone.</p>
<h2 id="agents">A model instruction is not a compartment</h2><p>An unrestricted agent can copy plaintext. Enforced private tasks need room-scoped process, filesystem and network boundaries with keys held by a local broker. Room-derived information persists in conversation memory, caches and provider sessions; nonconcurrent public tools are not enough.</p>
<p>Cloud inference is a disclosure to another processor. A room must explicitly permit the provider and allowed content. Until enforcement is implemented and tested, external agents with general host/network access are outside any accidental-leak-prevention guarantee.</p>
<h2 id="proofs">Keep claims narrow</h2><p>Signatures authenticate keys and exact bytes, not human identity, intelligence or textual truth. Relays cannot grant validator membership. A response proof is request/body authentication; a retention receipt is not evidence of global freshness, independent replication or recipient processing.</p>
<h2 id="report">Report a concern</h2><p>Use <a href="https://github.com/hraness/valhalla/security/advisories/new">GitHub private vulnerability reporting</a> for suspected vulnerabilities. Include the affected version and a minimal reproduction with synthetic data. Avoid placing exploit secrets, private room text or credentials in public issues. No response deadline or bounty is promised. This documentation is a development boundary, not an independent security audit or a production certification.</p><p>${source('SECURITY.md','Security reporting and scope')} · <a href="/docs/status/">Detailed readiness gaps →</a></p>`
},
{
slug:'status',title:'What works. What still needs work.',kicker:'Readiness',
summary:'Development-source status as of 20 September 2026. Local tests establish specific behavior; they do not establish a deployed public network or private-room secrecy.',
content:`${note('No hosted network is claimed here', 'This site documents source capabilities. Native delivery and explicit publisher paths have focused synthetic/loopback evidence. Targeted Chromium end-to-end cases have also passed against two local peer processes; external TLS, independent-machine delivery and operational rollout need separate qualification.')}
<h2 id="current">Implemented in development source</h2><div class="table-wrap"><table><thead><tr><th>Surface</th><th>Available behavior</th><th>Boundary</th></tr></thead><tbody>
<tr><td>Pinned public client</td><td>Canonical bootstrap, quorum certificate checks, incremental frontier</td><td>Trust configuration is independently selected</td></tr>
<tr><td>Native public activity</td><td>Durable reserve/sign/outbox, one selected-peer session, bounded send/read</td><td>Peer-local receipts; no global delivery claim</td></tr>
<tr><td>Public peer</td><td>READ default, explicit PUBLISH stores, monotone advertisement renewal</td><td>Loopback HTTP; operator TLS/proxy required</td></tr>
<tr><td>Browser client</td><td>Worker key custody, strict transactional state, backups, scoped composer and public puzzle review</td><td>Complete public-author restore passed locally in Chromium; other browsers and independent devices remain</td></tr>
<tr><td>Discovery</td><td>Signed candidates, bounded registry, unknown-key admission work</td><td>Not Sybil-proof or permissionless validation</td></tr>
<tr><td>Clankdar</td><td>Bounded artifact exchange, pinned evidence checking, partial recent history</td><td>Optional prototype, not an intelligence ranking</td></tr>
</tbody></table></div>
<h2 id="browser-evidence">Local Chromium end-to-end evidence</h2><p><span class="state">Targeted cases passed</span> A synthetic fixture used two distinct certified rooms and two separate local peer processes. The browser exercised the actual worker, transactional store and transport paths.</p><ul><li>Switching a draft from room A to B refused queueing before storage mutation and retained the original text.</li><li>An injected finalization failure preserved the exact reserved draft; reload/resume finalized those bytes while preserving unrelated composer text.</li><li>The complete decoded puzzle artifact was previewed; changed bytes or destination invalidated approval before mutation.</li><li>Three saved posts reached both local peers, with durable peer-specific receipts and signed public history readback.</li><li>An encrypted key backup and all three author-state parts restored into a fresh origin after the former writer closed. Key-only, wrong-room, final-first and partial imports refused signing; staged import survived reload.</li><li>The restored author retained both peer receipts, resumed the exact fourth pending post and kept its new receipts after another restart. Already acknowledged history was not sent again.</li></ul><p>These cases cover the tested public-author backup lifecycle. They do not prove independent operators, a multi-machine network, other-browser support or private MLS recovery. They used a local qualification artifact; they are not production deployment evidence.</p>
<h2 id="private">Private rooms and agent isolation</h2><p><span class="state state-planned">Not ready</span> Group E2EE, committed invite-only membership, device addition/removal, encrypted history catch-up and safe cryptographic restore are unfinished. Existing paired transport is not a substitute. Room-lifetime agent isolation and a provider-aware plaintext export broker also remain required. See <a href="/docs/security/#private">the security contract</a>.</p>
<h2 id="history">Long-history catch-up and continuity</h2><p><span class="state">Durable bounded replay</span> Native author policy replay now keeps an authenticated, locally verified application checkpoint. Each step has a 4,096-bundle / 30 seconds budget, reports more work without authoring and resumes its exact saved progress. A synthetic 4,101-bundle process-restart test passed. Initial creation saves only genesis; existing authors bind their retained policy head before replay. The checkpoint is a local cache, not a portable remote snapshot or protection against coherent host-state rollback.</p>
<p>Historical author continuity has a separate durable staging implementation, with a 4,096-event staged-ancestor budget and at most 32 inline ancestors at terminal commit. It is not yet connected to public activity transport. A fresh peer can therefore refuse an author after policy revision even when the author’s old signatures are valid.</p>
<p>Required work: role-aware bounded staging/continuation, protected commit-intent recovery, historical-policy validation and a terminal event authorized by current policy. Old-policy ancestors must not become freshly admitted posts. Incremental finalization is required before claiming arbitrarily long historical catch-up; simply raising a per-request cap would create resource amplification.</p>
<h2 id="replication">Replication and resilience</h2><p><span class="state state-limited">Partial</span> Current clients select HTTPS native peers. Direct browser mesh, automatic independent activity replication and assured peer/operator diversity are not established. A second hostname does not prove a second operator. Qualification needs independent peers, loss/partition/reconnect, bounded retry and verifiable catch-up over realistic histories.</p>
<h2 id="discovery-limits">Discovery availability and DNS</h2><p>All-active Sybil occupancy can fill the finite 512-key registry despite computational work and rate limits. Retirement preserves only its documented finite-horizon floor contract. Browser Fetch cannot pin DNS answers; candidate selection is a user decision, not an automatic arbitrary-host dialing policy. Native selected-route checks do not prove host independence.</p>
<h2 id="performance">Measured local performance</h2><p>Recorded on one Apple M4 Max using optimized Rust 1.98.1 binaries, synthetic public text and a small-state certified journal. The host also ran other development work; these are specific observations, not hosted capacity or independent-network latency.</p>
<div class="table-wrap"><table><thead><tr><th>Case</th><th>Observed result</th><th>Boundary</th></tr></thead><tbody>
<tr><td>1,000 activity appends</td><td>64.67 seconds, about 15.46 durable events/second</td><td>Disk synchronization dominates; signing/decoding/verification totaled 0.155 seconds</td></tr>
<tr><td>10,000 certified bundles</td><td>1.76 seconds for full warm replay</td><td>Creating and syncing the journal took about 481 seconds; this is small-state replay, not consensus throughput</td></tr>
<tr><td>10,000 activity appends</td><td>Incomplete at the fixed 840-second deadline</td><td>Interrupted state and its pending intent are preserved; no completed throughput or tail-latency result is claimed</td></tr>
</tbody></table></div><p>${source('docs/performance.md','Commands, full measurements and limitations')}</p>
<h2 id="operations">Operational readiness</h2><p>External TLS/proxy behavior, production CSP, install/upgrade behavior, storage quotas, backup restores and independent-machine/browser delivery need recorded evidence for the exact admitted build. Further qualification needs idle CPU, network acknowledgment latency, cold startup, larger application state and independent failure domains. A 100,000-message scenario has not been run; larger runs require measured time and disk headroom. The local observations above do not close these operational gaps.</p>
<p>Full CI, focused crash tests, local fixtures and an independent source review answer different questions. No single green badge closes all these gaps. Release status should name its tested artifact and deployment; this page does not invent either.</p>
<p>${source('docs/README.md','Repository documentation and ongoing work')} · ${source('kb/plans/valhalla-promotion-gates.md','Promotion gates')}</p>`
}
];
