#!/usr/bin/env python3
"""Package generated Trunk glue for a script-self-only static application origin."""
import argparse
import hashlib
import json
from pathlib import Path
import re

CSP = "; ".join([
    "default-src 'none'", "script-src 'self' 'wasm-unsafe-eval'",
    "style-src 'self'", "worker-src 'self'", "connect-src 'self' https:",
    "img-src 'self'", "base-uri 'none'", "form-action 'none'",
    "frame-ancestors 'none'", "object-src 'none'",
])
HEADERS = {
    "Content-Security-Policy": CSP,
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "no-referrer",
    "Permissions-Policy": "camera=(), microphone=(), geolocation=(), payment=(), usb=()",
    "Cross-Origin-Opener-Policy": "same-origin",
    # All persisted application identity/history stays under browser control.
    # Revalidation also prevents obsolete HTML from referring to deleted assets.
    "Cache-Control": "no-cache",
}


def package(root: Path, allow_local_qualification: bool = False) -> None:
    local = any(b"/__qualification/" in p.read_bytes() for p in root.glob("*.wasm"))
    if local and not allow_local_qualification:
        raise ValueError("local qualification routes cannot enter a production artifact")
    html_file = root / "index.html"
    html = html_file.read_text(encoding="utf-8")
    scripts = list(re.finditer(r'<script type="module">(.*?)</script>', html, re.S))
    if len(scripts) != 1 or len(re.findall(r"<script\b", html, re.I)) != 1:
        raise ValueError("expected exactly one generated Trunk module bootstrap")
    # Move the exact generated bytes, without interpreting or authoring JS.
    match = scripts[0]
    glue = match.group(1).encode("utf-8")
    digest = hashlib.sha256(glue).hexdigest()
    name = "bootstrap-" + digest[:24] + ".js"
    (root / name).write_bytes(glue)
    html = html[:match.start()] + '<script type="module" src="/' + name + '"></script>' + html[match.end():]
    if re.search(r"\son[a-z]+\s*=|javascript:", html, re.I):
        raise ValueError("inline script handlers are forbidden")
    html_file.write_text(html, encoding="utf-8")
    (root / "_headers").write_text("/*\n" + "".join("  " + k + ": " + v + "\n" for k, v in HEADERS.items()), encoding="utf-8")
    # Deploy this directory as a standalone static Vercel project, never over the
    # marketing site. The provider config is consumed at the artifact root.
    config = {"version": 2, "headers": [{"source": "/(.*)", "headers": [
        {"key": k, "value": v} for k, v in HEADERS.items()
    ]}]}
    (root / "vercel.json").write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    assets = {}
    for path in sorted(root.iterdir()):
        if path.is_file() and path.name != "artifact.json":
            assets[path.name] = {"bytes": path.stat().st_size, "sha256": hashlib.sha256(path.read_bytes()).hexdigest()}
    (root / "artifact.json").write_text(json.dumps({"format": 1, "purpose": "local-qualification" if local else "production", "assets": assets}, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("directory", type=Path)
    parser.add_argument("--allow-local-qualification", action="store_true", help="local QA only; never deploy this artifact")
    args = parser.parse_args()
    package(args.directory.resolve(strict=True), args.allow_local_qualification)
